version: '3.6'
services:
  db:
    container_name: dbNotee2
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

